version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-311:latest


dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.6
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
