- name: check if / is read-only
  hosts: clients
  become: true
  gather_facts: false

  tasks:
    - name: check root mount options
      ansible.builtin.command: findmnt -no OPTIONS /
      register: mount_opts

    - debug:
        var: mount_opts.stdout
