- name: Gather /etc write diagnostics
  hosts: clients
  gather_facts: false
  become: true

  tasks:
    - name: whoami and id
      ansible.builtin.command: id
      register: id_out

    - name: print whoami
      ansible.builtin.shell: whoami && echo "BEcome user $SUDO_USER"
      register: whoami_out
      ignore_errors: yes

    - name: stat /etc and /etc/motd
      ansible.builtin.command: stat -c "%n mode=%A uid=%u gid=%g" /etc /etc/motd
      register: stat_out
      ignore_errors: yes

    - name: ls -ld /etc
      ansible.builtin.command: ls -ld /etc
      register: lsld_out

    - name: check mounts
      ansible.builtin.command: mount | grep " / " || true
      register: mount_out

    - name: check immutable attributes (lsattr)
      ansible.builtin.command: lsattr -d /etc || true
      register: lsattr_out
      ignore_errors: yes

    - name: check if /etc is symlink
      ansible.builtin.command: readlink -f /etc || true
      register: readlink_out
      ignore_errors: yes

    - name: show SELinux mode
      ansible.builtin.shell: getenforce || echo "getenforce not found"
      register: selinux_out
      ignore_errors: yes

    - name: debug results
      ansible.builtin.debug:
        msg:
          - "{{ id_out.stdout_lines }}"
          - "{{ whoami_out.stdout_lines | default([]) }}"
          - "{{ stat_out.stdout_lines | default([]) }}"
          - "{{ lsld_out.stdout_lines }}"
          - "{{ mount_out.stdout_lines }}"
          - "{{ lsattr_out.stdout_lines | default([]) }}"
          - "{{ readlink_out.stdout_lines | default([]) }}"
          - "{{ selinux_out.stdout_lines | default([]) }}"
